### ISSUE TITLE
Pip install -r requirements.txt vs Pip3 install -r requirements

### ISSUE THREAD

**Issue by bCom5** [hydro-project/cloudburst#28]
I'm following the getting started guide, which uses `pip install -r requirements.txt`, I wasn't able to run it but using `pip3 install -r requirements.txt` does.

This is on a new Ubuntu 18.04 LTS EC2 t2.micro instance.

`pip install -r requirements.txt`
... # downloads first few python packages
```
Could not find a version that satisfies the requirement pandas==0.25.1 (from -r requirements.txt (line 5)) (from versions: 0.1, 0.2b0, 0.2b1, 0.2, 0.3.0b0, 0.3.0b2, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.6.0, 0.6.1, 0.7.0rc1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0rc1, 0.8.0rc2, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.16.2, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0rc1, 0.19.0, 0.19.1, 0.19.2, 0.20.0rc1, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.21.0rc1, 0.21.0, 0.21.1, 0.22.0, 0.23.0rc2, 0.23.0, 0.23.1, 0.23.2, 0.23.3, 0.23.4, 0.24.0rc1, 0.24.0, 0.24.1, 0.24.2)
No matching distribution found for pandas==0.25.1 (from -r requirements.txt (line 5))
```

**Comment by vsreekanti** [comment]
This might be because `pip` is installing for Python2, whereas `pip3` is installing for Python3. I don't know exactly what the versioning scheme differences are, but we've generally only been supporting Python3 for this project.

**Comment by vsreekanti** [comment]
Fixed with the clarifications in the instructions #29.
