### ISSUE TITLE
Getting Stuck on creating a CloudburstConnection object.

### ISSUE THREAD

**Issue by bCom5** [hydro-project/cloudburst#30]
In the README.md, there is
```python3
from cloudburst.client.client import CloudburstConnection
local_cloud = CloudburstConnection('127.0.0.1', '127.0.0.1', local=True)
```

Running from the python3 repl, I get stuck in the CloudburstConnection line.

In the [function execution doc](https://github.com/hydro-project/cloudburst/blob/master/docs/function-execution.md), it instructs

```python3
local = True # or False if you are running against a HydroCluster
elb_address = '127.0.0.1 ' # or the address of the ELB returned by the 
from cloudburst.client.client import CloudburstConnectioncloudburst = CloudburstConnection(AWS_FUNCTION_ELB, MY_IP, local=local)
```
 Do you need a elb for this? Can you run this locally using '127.0.0.1', '127.0.0.1'? Both examples set `local=True`

**Comment by vsreekanti** [comment]
Hi @bCom5 -- if you look at running processes (e.g., `ps -ef | grep cloudburst`), do you see both the scheduler and executor processes running? 

Using `127.0.0.1` for both addresses should work, so it's likely a configuration issue.

**Comment by bCom5** [comment]
![](https://i.imgur.com/MYGwDP7.png)

Ok, they seem to both be running. This is an example of how it gets stuck.

**Comment by vsreekanti** [comment]
Just to make sure, you are running a local version of Anna too, correct?

**Comment by bCom5** [comment]
Yes, that is correct.

**Comment by vsreekanti** [comment]
Can you use the [Anna client](https://github.com/hydro-project/anna/tree/master/client/python) to run some simple PUTs and GETs to make sure Anna is working correctly?
